# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ECCB 2026 Geneva Tutorial Book
author: https://biomedicalinformaticsgroup.github.io/
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: false
  timeout: 300

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/biomedicalinformaticsgroup/networks_ismb24.git  # Online location of your book 
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image
    - dollarmath
    - amsmath

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  config:
    html_theme: pydata_sphinx_theme
    html_theme_options:
      logo: 
        alt_text: "ECCB'26 T8"
        text: "Multi-Omics 2 Discovery via LLM"
        image_light: logo.svg
        image_dark: logo.svg
      navbar_center: ["navbar-icon-links", "navbar-nav"]
      navbar_end: ["theme-switcher"]
      icon_links:
        - name: Home
          url: /index.html
          icon: fas fa-home
          type: fontawesome
          attributes:
            target: _self
        - name: GitHub
          url: https://github.com/Barry8197/ECCB2026_TEST
          icon: fa-brands fa-square-github
          type: fontawesome
    add_module_names: True
    html_static_path: ['_static']
  local_extensions:
    s1_helpers : "./session-1-intro-networks"
    s2_helpers : "./session-2-multi-omics"
    s3_helpers : "./session-3-agentic-llm-workflows"
